import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Open_Sans, Lato } from "next/font/google";
import "./globals.css";
import { Weight } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto=Roboto({
  weight:'400',
  subsets:['latin']
})

const lato=Lato({
  weight:'400',
  subsets:['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={`${lato.className} h-screen antialiased pr-5 `} >
        {children}
      </body>
    </html>
  );
}
